baseURL = "https://thanithamizhakarathikalanjiyam.github.io/more_books/"
languageCode = "en-us"
theme = "kitab"
title = "ஞாலக் களஞ்சியம்"

disableKinds = ["taxonomy", "taxonomyTerm"]
pluralizelisttitles = false

[params]
  author = "Pitchaimuthu"
  description = "Tamil Collected books"
  dateFormat = "2006-01-02"
  footer1 = "Tamil Awesome Books"
  footer2 = "My favorite books"